"""
Tests for sparse_svd's `center` parameter -- the fix for the most
significant issue found in this project: the paper's Methods section
describes implicit centering ("column means are incorporated
implicitly during matrix-vector multiplication"), but no such
mechanism existed anywhere in the actual code. Every real-dataset
result in the paper (Table 1, and the marker-gene kME findings) was
generated by a pipeline that normalizes, log1p's, and variance-scales
but never centers -- see benchmarks/centering_validation.py for the
full writeup and `core.py`'s `center` parameter docstring.
"""
import numpy as np
import pytest
import scipy.sparse as sp

from slice_lca.core import (
    sparse_svd,
    canonicalize_signs,
    _centered_matvec,
    _centered_rmatvec,
    _column_means,
)
from slice_lca.datasets import make_antagonistic_axis, make_hard_overlap_counts


def test_centered_matvec_matches_explicit_centering():
    rng = np.random.default_rng(0)
    n, p = 60, 35
    X_dense = rng.uniform(0, 5, (n, p))
    X_sparse = sp.csr_matrix(X_dense)
    v = rng.standard_normal(p)
    v /= np.linalg.norm(v)
    mu = _column_means(X_sparse)
    got = _centered_matvec(X_sparse, v, mu)
    expected = (X_dense - X_dense.mean(axis=0)) @ v
    np.testing.assert_allclose(got, expected, atol=1e-10)


def test_centered_rmatvec_matches_explicit_centering():
    rng = np.random.default_rng(0)
    n, p = 60, 35
    X_dense = rng.uniform(0, 5, (n, p))
    X_sparse = sp.csr_matrix(X_dense)
    u = rng.standard_normal(n)
    u /= np.linalg.norm(u)
    mu = _column_means(X_sparse)
    got = _centered_rmatvec(X_sparse, u, mu)
    expected = (X_dense - X_dense.mean(axis=0)).T @ u
    np.testing.assert_allclose(got, expected, atol=1e-10)


def test_center_default_is_false_and_unchanged():
    """sparse_svd's own default must stay center=False so every
    previously published number is reproduced exactly."""
    rng = np.random.default_rng(0)
    X = sp.csr_matrix(rng.standard_normal((100, 50)))
    U1, D1, V1 = sparse_svd(X, k=2, sparsity=0.1, random_state=0)
    U2, D2, V2 = sparse_svd(X, k=2, sparsity=0.1, random_state=0, center=False)
    np.testing.assert_array_equal(U1, U2)
    np.testing.assert_array_equal(V1, V2)


def test_center_true_reproduces_published_ablation_numbers_from_uncentered_input():
    """The strongest possible cross-check: feed sparse_svd the RAW
    (log1p'd but NOT explicitly centered) matrix with center=True, and
    confirm it reproduces the exact published 'SLICE (full)' ablation
    numbers (0.900, 0.999, 0.177, 0.247), which were originally
    generated by explicitly centering first. If implicit and explicit
    centering are truly equivalent, these must match exactly."""
    X, Xc_explicit, tA, tB, gA, gB = make_hard_overlap_counts(seed=42)
    Xlog = np.log1p(X.toarray())
    X_uncentered = sp.csr_matrix(Xlog)

    def cs(U, t):
        return max(abs(np.corrcoef(t, U[:, j])[0, 1]) for j in range(U.shape[1]) if np.std(U[:, j]) > 0)

    def gs(V, g):
        return max(abs(np.corrcoef(g, V[:, j])[0, 1]) for j in range(V.shape[1]) if np.std(V[:, j]) > 0)

    U, D, V = sparse_svd(X_uncentered, k=4, sparsity=0.02, random_state=0, center=True)
    U, V = canonicalize_signs(U, V)
    assert cs(U, tA) == pytest.approx(0.900, abs=1e-3)
    assert cs(U, tB) == pytest.approx(0.999, abs=1e-3)
    assert gs(V, gA) == pytest.approx(0.177, abs=1e-3)
    assert gs(V, gB) == pytest.approx(0.247, abs=1e-3)


def test_center_true_recovers_antagonistic_axis_that_center_false_misses():
    """The core finding: on data preprocessed the same way the paper's
    real pipeline does (normalized, log1p'd, variance-scaled, but not
    centered), center=False fails to recover a known signed axis;
    center=True on the SAME input recovers it well."""
    from slice_lca.preprocessing import normalize_log1p, scale_only

    X, S_true, W_true = make_antagonistic_axis(n_cells=1000, n_genes=500, snr=5.0, seed=0)
    X_dense = X.toarray()
    X_counts = np.maximum(X_dense - X_dense.min(), 0) + 0.1
    Xs = sp.csr_matrix(X_counts.astype(np.float32))
    X_pipeline = scale_only(normalize_log1p(Xs))

    def gene_corr(V):
        return max(abs(np.corrcoef(W_true[:, 0], V[:, j])[0, 1]) for j in range(V.shape[1]))

    U0, D0, V0 = sparse_svd(X_pipeline, k=1, sparsity=0.15, n_iter=100, tol=1e-4, random_state=0, center=False)
    U1, D1, V1 = sparse_svd(X_pipeline, k=1, sparsity=0.15, n_iter=100, tol=1e-4, random_state=0, center=True)

    assert gene_corr(V0) < 0.3   # fails without centering
    assert gene_corr(V1) > 0.85  # succeeds with centering, same input


def test_center_preserves_sparsity_no_densification():
    """_column_means must work directly on the sparse matrix without
    ever creating a dense copy of X itself."""
    rng = np.random.default_rng(0)
    X = sp.random(5000, 2000, density=0.02, format="csr", random_state=0, dtype=np.float32)
    mu = _column_means(X)
    assert mu.shape == (2000,)
    assert sp.issparse(X)  # X itself must remain untouched/sparse
